name: flake8

on:
  workflow_dispatch:
  pull_request:
  push:
  
jobs:
  linter:
    name: flake8 linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up python3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install and run flake 8
      run: |
        pip install flake8
        flake8 python --statistics
